[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#25C997"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#1A202C"
font = "sans serif"
